type CaptionCue = {
  start: number;
  end: number;
  text: string;
};

type CaptionTrack = {
  languageCode?: string;
  name?: string;
  kind?: string;
  isAutoGenerated: boolean;
  url?: string;
};

type ExtractResult = {
  ok: true;
  video: {
    id: string;
    title: string;
    duration: number;
    url: string;
    channelName?: string;
  };
  captions: CaptionCue[];
  captionTrack?: CaptionTrack;
  visualCandidateTimestamps: number[];
} | {
  ok: false;
  reason: "NO_VIDEO" | "NO_CAPTIONS" | "CAPTION_FETCH_FAILED";
  message: string;
};

type CaptureFramesResult = {
  ok: true;
  frames: Array<{
    timestamp: number;
    dataUrl: string;
    source: "tab-screenshot";
  }>;
} | {
  ok: false;
  message: string;
};

type YtClientConfig = {
  apiKey?: string;
  clientVersion?: string;
  clientName?: string;
  visitorData?: string;
  sessionIndex?: string;
  hl?: string;
  gl?: string;
};

const READY_KEY = "__VIDSCRIBE_CONTENT_READY__";
const ANDROID_INNERTUBE_CLIENT = {
  clientName: "ANDROID",
  clientVersion: "20.10.38",
  clientNameHeader: "3"
} as const;
const MAX_VISUAL_CANDIDATES = 10;
const VISUAL_CUE_PATTERN =
  /\b(as shown|as you can see|look at|look here|on screen|shown here|diagram|slide|chart|graph|figure|code|example|visual|screenshot)\b/i;

const globalState = globalThis as typeof globalThis & Record<string, boolean>;

if (!globalState[READY_KEY]) {
  globalState[READY_KEY] = true;
  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message?.type === "VIDSCRIBE_EXTRACT") {
      extractCurrentVideo().then(sendResponse);
      return true;
    }

    if (message?.type === "VIDSCRIBE_CAPTURE_FRAMES") {
      captureFrames(message.timestamps ?? []).then(sendResponse);
      return true;
    }

    if (message?.type === "VIDSCRIBE_SEEK") {
      seekTo(Number(message.timestamp ?? 0));
      sendResponse({ ok: true });
      return false;
    }

    if (message?.type === "VIDSCRIBE_PING") {
      sendResponse({ ok: true });
      return false;
    }

    return undefined;
  });
}

function getVideoElement(): HTMLVideoElement | null {
  return document.querySelector("video");
}

function getVideoIdFromUrl(): string | undefined {
  const parsed = new URL(window.location.href);
  return parsed.searchParams.get("v") ?? undefined;
}

function readTextRenderer(renderer: any): string | undefined {
  if (!renderer) return undefined;
  if (typeof renderer.simpleText === "string") return renderer.simpleText;
  if (Array.isArray(renderer.runs)) {
    return renderer.runs.map((run: any) => run.text).filter(Boolean).join("");
  }
  return undefined;
}

function safeJsonString(raw: string | undefined): string | undefined {
  if (!raw) return undefined;

  try {
    return JSON.parse(`"${raw}"`) as string;
  } catch {
    return raw;
  }
}

function extractBalancedJson(source: string, startIndex: number): string | undefined {
  const firstBrace = source.indexOf("{", startIndex);
  if (firstBrace === -1) return undefined;

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let index = firstBrace; index < source.length; index += 1) {
    const char = source[index];

    if (escaped) {
      escaped = false;
      continue;
    }

    if (char === "\\") {
      escaped = true;
      continue;
    }

    if (char === '"') {
      inString = !inString;
      continue;
    }

    if (inString) continue;

    if (char === "{") depth += 1;
    if (char === "}") depth -= 1;

    if (depth === 0) {
      return source.slice(firstBrace, index + 1);
    }
  }

  return undefined;
}

function getPlayerResponseFromScripts(): any | undefined {
  for (const script of Array.from(document.scripts)) {
    const text = script.textContent ?? "";
    const markerIndex = text.indexOf("ytInitialPlayerResponse");
    if (markerIndex === -1) continue;

    const jsonText = extractBalancedJson(text, markerIndex);
    if (!jsonText) continue;

    try {
      return JSON.parse(jsonText);
    } catch {
      continue;
    }
  }

  return undefined;
}

function getInitialDataFromScripts(): any | undefined {
  for (const script of Array.from(document.scripts)) {
    const text = script.textContent ?? "";
    const markerIndex = text.indexOf("ytInitialData");
    if (markerIndex === -1) continue;

    const jsonText = extractBalancedJson(text, markerIndex);
    if (!jsonText) continue;

    try {
      return JSON.parse(jsonText);
    } catch {
      continue;
    }
  }

  return undefined;
}

function getYtClientConfigFromScripts(): YtClientConfig {
  const config: YtClientConfig = {};

  for (const script of Array.from(document.scripts)) {
    const text = script.textContent ?? "";
    if (!text.includes("INNERTUBE_API_KEY")) continue;

    config.apiKey ??= safeJsonString(
      /"INNERTUBE_API_KEY"\s*:\s*"([^"]+)"/.exec(text)?.[1]
    );
    config.clientVersion ??= safeJsonString(
      /"INNERTUBE_CLIENT_VERSION"\s*:\s*"([^"]+)"/.exec(text)?.[1]
    );
    config.clientName ??= safeJsonString(
      /"INNERTUBE_CONTEXT_CLIENT_NAME"\s*:\s*(?:"([^"]+)"|(\d+))/.exec(text)?.[1] ??
        /"INNERTUBE_CONTEXT_CLIENT_NAME"\s*:\s*(?:"([^"]+)"|(\d+))/.exec(text)?.[2]
    );
    config.visitorData ??= safeJsonString(
      /"VISITOR_DATA"\s*:\s*"([^"]+)"/.exec(text)?.[1]
    );
    config.sessionIndex ??= safeJsonString(
      /"SESSION_INDEX"\s*:\s*"([^"]+)"/.exec(text)?.[1]
    );
    config.hl ??= safeJsonString(/"HL"\s*:\s*"([^"]+)"/.exec(text)?.[1]);
    config.gl ??= safeJsonString(/"GL"\s*:\s*"([^"]+)"/.exec(text)?.[1]);

    if (config.apiKey && config.clientVersion) {
      break;
    }
  }

  return config;
}

function getInnertubeHeaders(clientConfig: YtClientConfig): Record<string, string> {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    "X-YouTube-Client-Name": clientConfig.clientName ?? "1",
    "X-YouTube-Client-Version":
      clientConfig.clientVersion ?? "2.20260626.01.00"
  };

  if (clientConfig.visitorData) {
    headers["X-Goog-Visitor-Id"] = clientConfig.visitorData;
  }

  if (clientConfig.sessionIndex) {
    headers["X-Goog-AuthUser"] = clientConfig.sessionIndex;
  }

  return headers;
}

function getInnertubeContext(clientConfig: YtClientConfig) {
  return {
    client: {
      clientName: "WEB",
      clientVersion: clientConfig.clientVersion ?? "2.20260626.01.00",
      hl: clientConfig.hl ?? "en",
      gl: clientConfig.gl ?? "US",
      visitorData: clientConfig.visitorData
    },
    user: {
      lockedSafetyMode: false
    },
    request: {
      useSsl: true,
      internalExperimentFlags: [],
      consistencyTokenJars: []
    }
  };
}

async function fetchCaptionTracksFromAndroidInnertube(
  videoId: string
): Promise<any[]> {
  const clientConfig = getYtClientConfigFromScripts();
  if (!clientConfig.apiKey) {
    console.warn("[VidScribe] Could not find YouTube Innertube API key for ANDROID client");
    return [];
  }

  const endpoint = new URL("/youtubei/v1/player", window.location.origin);
  endpoint.searchParams.set("key", clientConfig.apiKey);
  endpoint.searchParams.set("prettyPrint", "false");

  const response = await fetch(endpoint.toString(), {
    method: "POST",
    credentials: "include",
    headers: {
      "Content-Type": "application/json",
      "X-YouTube-Client-Name": ANDROID_INNERTUBE_CLIENT.clientNameHeader,
      "X-YouTube-Client-Version": ANDROID_INNERTUBE_CLIENT.clientVersion,
      "User-Agent": `com.google.android.youtube/${ANDROID_INNERTUBE_CLIENT.clientVersion} (Linux; U; Android 14) gzip`
    },
    body: JSON.stringify({
      context: {
        client: {
          clientName: ANDROID_INNERTUBE_CLIENT.clientName,
          clientVersion: ANDROID_INNERTUBE_CLIENT.clientVersion,
          hl: clientConfig.hl ?? "en",
          gl: clientConfig.gl ?? "US"
        }
      },
      videoId,
      contentCheckOk: true,
      racyCheckOk: true
    })
  });

  if (!response.ok) {
    console.warn(
      `[VidScribe] ANDROID player request failed with ${response.status}`
    );
    return [];
  }

  const payload = await response.json();
  const tracks = getCaptionTracks(payload);
  console.info(
    `[VidScribe] ANDROID Innertube returned ${tracks.length} caption track(s)`
  );
  return tracks;
}

async function fetchPlayerResponseFromInnertube(
  videoId: string
): Promise<any | undefined> {
  const clientConfig = getYtClientConfigFromScripts();
  if (!clientConfig.apiKey) {
    console.warn("[VidScribe] Could not find YouTube Innertube API key");
    return undefined;
  }

  const endpoint = new URL("/youtubei/v1/player", window.location.origin);
  endpoint.searchParams.set("key", clientConfig.apiKey);
  endpoint.searchParams.set("prettyPrint", "false");

  const response = await fetch(endpoint.toString(), {
    method: "POST",
    credentials: "include",
    headers: getInnertubeHeaders(clientConfig),
    body: JSON.stringify({
      context: getInnertubeContext(clientConfig),
      videoId,
      contentCheckOk: true,
      racyCheckOk: true
    })
  });

  if (!response.ok) {
    console.warn(
      `[VidScribe] YouTube player request failed with ${response.status}`
    );
    return undefined;
  }

  return response.json();
}

async function getPlayerResponse(videoId: string): Promise<any | undefined> {
  const scriptedPlayerResponse = getPlayerResponseFromScripts();
  const scriptedVideoId = scriptedPlayerResponse?.videoDetails?.videoId;
  const scriptedTracks = getCaptionTracks(scriptedPlayerResponse);

  if (scriptedVideoId === videoId && scriptedTracks.length > 0) {
    return scriptedPlayerResponse;
  }

  const innertubePlayerResponse = await fetchPlayerResponseFromInnertube(videoId);
  if (innertubePlayerResponse) {
    return innertubePlayerResponse;
  }

  return scriptedVideoId === videoId ? scriptedPlayerResponse : undefined;
}

function getCaptionTracks(playerResponse: any): any[] {
  return (
    playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []
  );
}

function chooseCaptionTrack(tracks: any[]): any | undefined {
  const englishManual = tracks.find(
    (track) =>
      track.languageCode?.startsWith("en") &&
      track.kind !== "asr" &&
      track.baseUrl
  );
  if (englishManual) return englishManual;

  const englishAuto = tracks.find(
    (track) =>
      track.languageCode?.startsWith("en") &&
      track.kind === "asr" &&
      track.baseUrl
  );
  if (englishAuto) return englishAuto;

  return tracks.find((track) => Boolean(track.baseUrl));
}

function normalizeTrack(track: any): CaptionTrack {
  return {
    languageCode: track.languageCode,
    name: readTextRenderer(track.name),
    kind: track.kind,
    isAutoGenerated: track.kind === "asr",
    url: track.baseUrl
  };
}

function parseJson3Captions(payload: any): CaptionCue[] {
  const cues: CaptionCue[] = [];

  for (const event of payload.events ?? []) {
    const text = (event.segs ?? [])
      .map((segment: any) => segment.utf8 ?? "")
      .join("")
      .replace(/\s+/g, " ")
      .trim();

    if (!text) continue;

    const start = Number(event.tStartMs ?? 0) / 1000;
    const duration = Number(event.dDurationMs ?? 2000) / 1000;
    cues.push({
      start,
      end: start + Math.max(0.25, duration),
      text
    });
  }

  return cues;
}

function textFromRenderer(renderer: any): string {
  return normalizeCaptionText(readTextRenderer(renderer) ?? "");
}

function normalizeCaptionText(text: string): string {
  return text.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
}

function textFromXmlCaptionNode(node: Element): string {
  const segments = Array.from(node.querySelectorAll("s"))
    .map((segment) => segment.textContent ?? "")
    .filter((segment) => segment.trim().length > 0);

  return normalizeCaptionText(
    segments.length > 0 ? segments.join(" ") : node.textContent ?? ""
  );
}

function parseXmlCaptions(xmlText: string): CaptionCue[] {
  const doc = new DOMParser().parseFromString(xmlText, "text/xml");
  if (doc.querySelector("parsererror")) {
    throw new Error("Caption XML parser error");
  }

  const textNodes = Array.from(doc.querySelectorAll("text"));
  const legacyCues = textNodes
    .map((node) => {
      const start = Number(node.getAttribute("start") ?? 0);
      const duration = Number(node.getAttribute("dur") ?? 2);
      const text = normalizeCaptionText(node.textContent ?? "");

      return {
        start,
        end: start + Math.max(0.25, duration),
        text
      };
    })
    .filter((cue) => cue.text.length > 0);

  if (legacyCues.length > 0) {
    return legacyCues;
  }

  const paragraphNodes = Array.from(doc.querySelectorAll("p"));
  return paragraphNodes
    .map((node) => {
      const start = Number(node.getAttribute("t") ?? 0) / 1000;
      const duration = Number(node.getAttribute("d") ?? 2000) / 1000;
      const text = textFromXmlCaptionNode(node);

      return {
        start,
        end: start + Math.max(0.25, duration),
        text
      };
    })
    .filter((cue) => cue.text.length > 0);
}

function parseVttTimestamp(timestamp: string): number {
  const parts = timestamp.trim().split(":");
  const secondsPart = parts.pop() ?? "0";
  const minutesPart = parts.pop() ?? "0";
  const hoursPart = parts.pop() ?? "0";

  return (
    Number(hoursPart) * 3600 +
    Number(minutesPart) * 60 +
    Number(secondsPart.replace(",", "."))
  );
}

function parseVttCaptions(vttText: string): CaptionCue[] {
  const cues: CaptionCue[] = [];
  const blocks = vttText.replace(/^WEBVTT.*$/m, "").split(/\n\s*\n/g);

  for (const block of blocks) {
    const lines = block
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean);
    const timingIndex = lines.findIndex((line) => line.includes("-->"));
    if (timingIndex === -1) continue;

    const timingLine = lines[timingIndex];
    if (!timingLine) continue;

    const [startRaw, endRaw] = timingLine.split("-->").map((part) => part.trim());
    if (!startRaw || !endRaw) continue;

    const cueText = normalizeCaptionText(lines.slice(timingIndex + 1).join(" "));
    if (!cueText) continue;

    cues.push({
      start: parseVttTimestamp(startRaw.split(/\s+/)[0] ?? "0"),
      end: parseVttTimestamp(endRaw.split(/\s+/)[0] ?? "0"),
      text: cueText
    });
  }

  return cues;
}

function trackLabel(track: any): string {
  const label = readTextRenderer(track?.name) ?? track?.languageCode ?? "unknown";
  const kind = track?.kind ? `/${track.kind}` : "";
  return `${label}${kind}`;
}

function orderedCaptionTracks(tracks: any[]): any[] {
  const preferred = chooseCaptionTrack(tracks);
  const seen = new Set<string>();
  const ordered = preferred ? [preferred, ...tracks] : tracks;

  return ordered.filter((track) => {
    if (!track?.baseUrl || seen.has(track.baseUrl)) {
      return false;
    }

    seen.add(track.baseUrl);
    return true;
  });
}

function parseCaptionBody(body: string, format: string): CaptionCue[] {
  const trimmed = body.trim();
  if (!trimmed) {
    throw new Error(`Caption ${format} response was empty`);
  }

  if (format === "provided") {
    if (trimmed.startsWith("{")) {
      return parseJson3Captions(JSON.parse(trimmed));
    }
    if (trimmed.startsWith("WEBVTT")) {
      return parseVttCaptions(trimmed);
    }
    return parseXmlCaptions(trimmed);
  }

  if (format === "json3") {
    return parseJson3Captions(JSON.parse(trimmed));
  }
  if (format === "vtt") {
    return parseVttCaptions(trimmed);
  }

  return parseXmlCaptions(trimmed);
}

async function fetchCaptionText(track: any, format?: string): Promise<string> {
  const url = new URL(track.baseUrl);
  // ANDROID timedtext URLs already include fmt=srv3; strip before overriding.
  url.searchParams.delete("fmt");
  if (format) {
    url.searchParams.set("fmt", format);
  }

  const attemptLabel = format ?? "provided";
  try {
    const directBody = await fetchCaptionTextFromPage(url, attemptLabel);
    if (directBody.trim()) {
      return directBody;
    }

    console.warn(
      `[VidScribe] ${attemptLabel} page fetch returned empty; trying extension fetch`
    );
  } catch (error) {
    console.warn(
      `[VidScribe] ${attemptLabel} page fetch failed; trying extension fetch`,
      error
    );
  }

  return fetchCaptionTextFromExtension(url, attemptLabel);
}

async function fetchCaptionTextFromPage(
  url: URL,
  attemptLabel: string
): Promise<string> {
  const response = await fetch(url.toString(), {
    credentials: "include",
    headers: {
      Accept: "application/json,text/xml,text/vtt,text/plain,*/*"
    }
  });
  const body = await response.text();

  console.info("[VidScribe] Caption page fetch", {
    attempt: attemptLabel,
    status: response.status,
    length: body.length
  });

  if (!response.ok) {
    throw new Error(`Caption ${attemptLabel} request failed with ${response.status}`);
  }

  return body;
}

async function fetchCaptionTextFromExtension(
  url: URL,
  attemptLabel: string
): Promise<string> {
  const response = await chrome.runtime.sendMessage({
    type: "VIDSCRIBE_FETCH_YOUTUBE_CAPTION",
    url: url.toString()
  });

  const body = String(response?.body ?? "");
  console.info("[VidScribe] Caption extension fetch", {
    attempt: attemptLabel,
    status: response?.status,
    ok: Boolean(response?.ok),
    length: body.length
  });

  if (!response?.ok) {
    throw new Error(response?.error ?? `Caption ${attemptLabel} extension fetch failed`);
  }

  return body;
}

async function fetchCaptionsFromTrack(track: any): Promise<CaptionCue[]> {
  const attempts = ["provided", "json3", "srv3", "srv1", "vtt"];
  const errors: string[] = [];

  for (const attempt of attempts) {
    try {
      const body = await fetchCaptionText(
        track,
        attempt === "provided" ? undefined : attempt
      );
      const cues = parseCaptionBody(body, attempt);
      console.info(
        `[VidScribe] Parsed ${cues.length} caption cue(s) from ${attempt} for ${trackLabel(track)}`
      );

      if (cues.length > 0) {
        return cues;
      }

      errors.push(`${attempt}: parsed 0 cues`);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      errors.push(`${attempt}: ${message}`);
      console.warn(
        `[VidScribe] ${attempt} captions failed for ${trackLabel(track)}`,
        error
      );
    }
  }

  throw new Error(`${trackLabel(track)} attempts failed: ${errors.join("; ")}`);
}

async function fetchCaptionsFromTracks(
  tracks: any[]
): Promise<{ captions: CaptionCue[]; track: any }> {
  const errors: string[] = [];

  for (const track of orderedCaptionTracks(tracks)) {
    try {
      console.info("[VidScribe] Trying caption track", {
        languageCode: track?.languageCode,
        name: readTextRenderer(track?.name),
        kind: track?.kind,
        hasBaseUrl: Boolean(track?.baseUrl)
      });
      const captions = await fetchCaptionsFromTrack(track);
      return { captions, track };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      errors.push(message);
    }
  }

  throw new Error(`No usable caption text. Tracks: ${errors.join(" | ")}`);
}

function findTranscriptParams(value: any, seen = new WeakSet<object>()): string | undefined {
  if (!value || typeof value !== "object") {
    return undefined;
  }

  if (seen.has(value)) {
    return undefined;
  }
  seen.add(value);

  const params = value?.getTranscriptEndpoint?.params;
  if (typeof params === "string" && params.length > 0) {
    return params;
  }

  if (Array.isArray(value)) {
    for (const item of value) {
      const found = findTranscriptParams(item, seen);
      if (found) return found;
    }
    return undefined;
  }

  for (const item of Object.values(value)) {
    const found = findTranscriptParams(item, seen);
    if (found) return found;
  }

  return undefined;
}

function collectRendererObjects(
  value: any,
  rendererName: string,
  output: any[] = [],
  seen = new WeakSet<object>()
): any[] {
  if (!value || typeof value !== "object") {
    return output;
  }

  if (seen.has(value)) {
    return output;
  }
  seen.add(value);

  if (value[rendererName]) {
    output.push(value[rendererName]);
  }

  if (Array.isArray(value)) {
    for (const item of value) {
      collectRendererObjects(item, rendererName, output, seen);
    }
    return output;
  }

  for (const item of Object.values(value)) {
    collectRendererObjects(item, rendererName, output, seen);
  }

  return output;
}

function parseTranscriptResponse(payload: any): CaptionCue[] {
  const cueRenderers = collectRendererObjects(payload, "transcriptCueRenderer");
  const cueCaptions = cueRenderers
    .map((renderer) => {
      const start = Number(renderer.startOffsetMs ?? renderer.startMs ?? 0) / 1000;
      const duration = Number(renderer.durationMs ?? 2000) / 1000;
      const text = textFromRenderer(renderer.cue ?? renderer.snippet);

      return {
        start,
        end: start + Math.max(0.25, duration),
        text
      };
    })
    .filter((cue) => cue.text.length > 0);

  if (cueCaptions.length > 0) {
    return cueCaptions;
  }

  const segmentRenderers = collectRendererObjects(payload, "transcriptSegmentRenderer");
  return segmentRenderers
    .map((renderer) => {
      const start = Number(renderer.startMs ?? 0) / 1000;
      const endMs = Number(renderer.endMs ?? 0);
      const durationMs = Number(renderer.durationMs ?? 0);
      const end =
        endMs > 0
          ? endMs / 1000
          : start + Math.max(0.25, (durationMs || 2000) / 1000);
      const text = textFromRenderer(renderer.snippet ?? renderer.cue);

      return {
        start,
        end,
        text
      };
    })
    .filter((cue) => cue.text.length > 0);
}

async function fetchTranscriptPanelCaptions(
  videoId: string
): Promise<{ captions: CaptionCue[]; track: any } | undefined> {
  const initialData = getInitialDataFromScripts();
  const params = findTranscriptParams(initialData);
  const clientConfig = getYtClientConfigFromScripts();

  if (!params || !clientConfig.apiKey) {
    console.warn("[VidScribe] Transcript panel fallback unavailable", {
      hasParams: Boolean(params),
      hasApiKey: Boolean(clientConfig.apiKey)
    });
    return undefined;
  }

  const endpoint = new URL("/youtubei/v1/get_transcript", window.location.origin);
  endpoint.searchParams.set("key", clientConfig.apiKey);
  endpoint.searchParams.set("prettyPrint", "false");

  const response = await fetch(endpoint.toString(), {
    method: "POST",
    credentials: "include",
    headers: getInnertubeHeaders(clientConfig),
    body: JSON.stringify({
      context: getInnertubeContext(clientConfig),
      params
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.warn(
      `[VidScribe] Transcript panel request failed with ${response.status}`,
      errorText.slice(0, 500)
    );
    return undefined;
  }

  const payload = await response.json();
  const captions = parseTranscriptResponse(payload);
  console.info(
    `[VidScribe] Parsed ${captions.length} caption cue(s) from transcript panel`
  );

  if (captions.length === 0) {
    return undefined;
  }

  return {
    captions,
    track: {
      languageCode: "unknown",
      name: { simpleText: "YouTube transcript" },
      kind: "transcript-panel",
      baseUrl: undefined
    }
  };
}

function chooseVisualCandidates(cues: CaptionCue[], duration: number): number[] {
  const semantic = cues
    .filter((cue) => VISUAL_CUE_PATTERN.test(cue.text))
    .map((cue) => cue.start)
    .slice(0, 6);

  const anchors: number[] = [];
  const anchorCount = Math.min(4, Math.max(1, Math.floor(duration / 600)));
  for (let index = 1; index <= anchorCount; index += 1) {
    anchors.push((duration * index) / (anchorCount + 1));
  }

  const merged = [...semantic, ...anchors]
    .filter((time) => Number.isFinite(time) && time >= 0 && time <= duration)
    .map((time) => Math.max(0, Math.min(duration - 0.5, time)));

  return Array.from(new Set(merged.map((time) => Math.round(time)))).slice(
    0,
    MAX_VISUAL_CANDIDATES
  );
}

async function extractCurrentVideo(): Promise<ExtractResult> {
  const videoElement = getVideoElement();
  const videoId = getVideoIdFromUrl();

  if (!videoElement || !videoId) {
    return {
      ok: false,
      reason: "NO_VIDEO",
      message: "Open a YouTube video to get started."
    };
  }

  const playerResponse = await getPlayerResponse(videoId);
  const videoDetails = playerResponse?.videoDetails;

  // WEB caption track URLs often include exp=xpe and require a PoToken, returning
  // empty 200 responses. ANDROID Innertube URLs do not have that restriction.
  let tracks = await fetchCaptionTracksFromAndroidInnertube(videoId);
  if (tracks.length === 0) {
    tracks = getCaptionTracks(playerResponse);
    console.warn(
      "[VidScribe] Falling back to page caption tracks (may require PoToken)"
    );
  }
  console.info(
    `[VidScribe] Found ${tracks.length} caption track(s) for video ${videoId}`
  );
  try {
    let extraction:
      | {
          captions: CaptionCue[];
          track: any;
        }
      | undefined;

    if (tracks.length > 0) {
      try {
        extraction = await fetchCaptionsFromTracks(tracks);
      } catch (error) {
        console.warn(
          "[VidScribe] Caption tracks failed; trying transcript panel fallback",
          error
        );
      }
    }

    extraction ??= await fetchTranscriptPanelCaptions(videoId);

    if (!extraction) {
      return {
        ok: false,
        reason: "NO_CAPTIONS",
        message: "This video has no captions. Audio transcription is not part of the MVP yet."
      };
    }

    const { captions, track: selectedTrack } = extraction;

    if (captions.length === 0) {
      return {
        ok: false,
        reason: "NO_CAPTIONS",
        message: "This video did not return usable caption text."
      };
    }

    const duration =
      Number(videoDetails?.lengthSeconds) ||
      Number(videoElement.duration) ||
      captions.at(-1)?.end ||
      0;

    return {
      ok: true,
      video: {
        id: videoId,
        title: videoDetails?.title ?? document.title.replace(" - YouTube", ""),
        duration,
        url: window.location.href,
        channelName: videoDetails?.author
      },
      captions,
      captionTrack: normalizeTrack(selectedTrack),
      visualCandidateTimestamps: chooseVisualCandidates(captions, duration)
    };
  } catch (error) {
    console.warn("[VidScribe] Caption extraction failed", error);
    return {
      ok: false,
      reason: "CAPTION_FETCH_FAILED",
      message: "Could not fetch captions for this video."
    };
  }
}

function wait(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function seekVideo(video: HTMLVideoElement, timestamp: number): Promise<void> {
  return new Promise((resolve) => {
    let settled = false;
    const finish = () => {
      if (settled) return;
      settled = true;
      video.removeEventListener("seeked", finish);
      resolve();
    };

    video.addEventListener("seeked", finish, { once: true });
    video.currentTime = timestamp;
    window.setTimeout(finish, 1500);
  });
}

async function captureVisibleTab(): Promise<string> {
  const response = await chrome.runtime.sendMessage({
    type: "VIDSCRIBE_CAPTURE_VISIBLE_TAB"
  });

  if (!response?.ok || !response.dataUrl) {
    throw new Error(response?.error ?? "Visible tab capture failed");
  }

  return response.dataUrl;
}

async function captureFrames(timestamps: number[]): Promise<CaptureFramesResult> {
  const video = getVideoElement();
  if (!video) {
    return { ok: false, message: "No video element found." };
  }

  const uniqueTimestamps = Array.from(
    new Set(
      timestamps
        .map((timestamp) => Number(timestamp))
        .filter((timestamp) => Number.isFinite(timestamp) && timestamp >= 0)
        .map((timestamp) =>
          Math.min(Math.max(0, timestamp), Math.max(0, video.duration - 0.5))
        )
    )
  ).slice(0, MAX_VISUAL_CANDIDATES);

  const originalTime = video.currentTime;
  const wasPaused = video.paused;
  const frames: Array<{
    timestamp: number;
    dataUrl: string;
    source: "tab-screenshot";
  }> = [];

  try {
    video.pause();

    for (const timestamp of uniqueTimestamps) {
      await seekVideo(video, timestamp);
      await wait(350);
      const dataUrl = await captureVisibleTab();
      frames.push({
        timestamp: video.currentTime,
        dataUrl,
        source: "tab-screenshot"
      });
    }

    return { ok: true, frames };
  } catch (error) {
    return {
      ok: false,
      message: error instanceof Error ? error.message : "Frame capture failed"
    };
  } finally {
    await seekVideo(video, originalTime);
    if (!wasPaused) {
      void video.play();
    }
  }
}

function seekTo(timestamp: number) {
  const video = getVideoElement();
  if (!video) return;
  video.currentTime = Math.max(0, Math.min(timestamp, video.duration || timestamp));
  void video.play();
}
