type CaptionCue = {
  start: number;
  end: number;
  text: string;
};

type CaptionTrack = {
  languageCode?: string;
  name?: string;
  kind?: string;
  isAutoGenerated: boolean;
  url?: string;
};

type ExtractResult = {
  ok: true;
  video: {
    id: string;
    title: string;
    duration: number;
    url: string;
    channelName?: string;
  };
  captions: CaptionCue[];
  captionTrack?: CaptionTrack;
  visualCandidateTimestamps: number[];
} | {
  ok: false;
  reason: "NO_VIDEO" | "NO_CAPTIONS" | "CAPTION_FETCH_FAILED";
  message: string;
};

type CaptureFramesResult = {
  ok: true;
  frames: Array<{
    timestamp: number;
    dataUrl: string;
    source: "tab-screenshot";
  }>;
} | {
  ok: false;
  message: string;
};

const READY_KEY = "__VIDSCRIBE_CONTENT_READY__";
const MAX_VISUAL_CANDIDATES = 10;
const VISUAL_CUE_PATTERN =
  /\b(as shown|as you can see|look at|look here|on screen|shown here|diagram|slide|chart|graph|figure|code|example|visual|screenshot)\b/i;

const globalState = globalThis as typeof globalThis & Record<string, boolean>;

if (!globalState[READY_KEY]) {
  globalState[READY_KEY] = true;
  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message?.type === "VIDSCRIBE_EXTRACT") {
      extractCurrentVideo().then(sendResponse);
      return true;
    }

    if (message?.type === "VIDSCRIBE_CAPTURE_FRAMES") {
      captureFrames(message.timestamps ?? []).then(sendResponse);
      return true;
    }

    if (message?.type === "VIDSCRIBE_SEEK") {
      seekTo(Number(message.timestamp ?? 0));
      sendResponse({ ok: true });
      return false;
    }

    if (message?.type === "VIDSCRIBE_PING") {
      sendResponse({ ok: true });
      return false;
    }

    return undefined;
  });
}

function getVideoElement(): HTMLVideoElement | null {
  return document.querySelector("video");
}

function getVideoIdFromUrl(): string | undefined {
  const parsed = new URL(window.location.href);
  return parsed.searchParams.get("v") ?? undefined;
}

function readTextRenderer(renderer: any): string | undefined {
  if (!renderer) return undefined;
  if (typeof renderer.simpleText === "string") return renderer.simpleText;
  if (Array.isArray(renderer.runs)) {
    return renderer.runs.map((run: any) => run.text).filter(Boolean).join("");
  }
  return undefined;
}

function extractBalancedJson(source: string, startIndex: number): string | undefined {
  const firstBrace = source.indexOf("{", startIndex);
  if (firstBrace === -1) return undefined;

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let index = firstBrace; index < source.length; index += 1) {
    const char = source[index];

    if (escaped) {
      escaped = false;
      continue;
    }

    if (char === "\\") {
      escaped = true;
      continue;
    }

    if (char === '"') {
      inString = !inString;
      continue;
    }

    if (inString) continue;

    if (char === "{") depth += 1;
    if (char === "}") depth -= 1;

    if (depth === 0) {
      return source.slice(firstBrace, index + 1);
    }
  }

  return undefined;
}

function getPlayerResponse(): any | undefined {
  for (const script of Array.from(document.scripts)) {
    const text = script.textContent ?? "";
    const markerIndex = text.indexOf("ytInitialPlayerResponse");
    if (markerIndex === -1) continue;

    const jsonText = extractBalancedJson(text, markerIndex);
    if (!jsonText) continue;

    try {
      return JSON.parse(jsonText);
    } catch {
      continue;
    }
  }

  return undefined;
}

function getCaptionTracks(playerResponse: any): any[] {
  return (
    playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []
  );
}

function chooseCaptionTrack(tracks: any[]): any | undefined {
  const englishManual = tracks.find(
    (track) =>
      track.languageCode?.startsWith("en") &&
      track.kind !== "asr" &&
      track.baseUrl
  );
  if (englishManual) return englishManual;

  const englishAuto = tracks.find(
    (track) =>
      track.languageCode?.startsWith("en") &&
      track.kind === "asr" &&
      track.baseUrl
  );
  if (englishAuto) return englishAuto;

  return tracks.find((track) => Boolean(track.baseUrl));
}

function normalizeTrack(track: any): CaptionTrack {
  return {
    languageCode: track.languageCode,
    name: readTextRenderer(track.name),
    kind: track.kind,
    isAutoGenerated: track.kind === "asr",
    url: track.baseUrl
  };
}

async function fetchCaptions(track: any): Promise<CaptionCue[]> {
  const url = new URL(track.baseUrl);
  url.searchParams.set("fmt", "json3");

  const response = await fetch(url.toString());
  if (!response.ok) {
    throw new Error(`Caption request failed with ${response.status}`);
  }

  const payload = await response.json();
  const cues: CaptionCue[] = [];

  for (const event of payload.events ?? []) {
    const text = (event.segs ?? [])
      .map((segment: any) => segment.utf8 ?? "")
      .join("")
      .replace(/\s+/g, " ")
      .trim();

    if (!text) continue;

    const start = Number(event.tStartMs ?? 0) / 1000;
    const duration = Number(event.dDurationMs ?? 2000) / 1000;
    cues.push({
      start,
      end: start + Math.max(0.25, duration),
      text
    });
  }

  return cues;
}

function chooseVisualCandidates(cues: CaptionCue[], duration: number): number[] {
  const semantic = cues
    .filter((cue) => VISUAL_CUE_PATTERN.test(cue.text))
    .map((cue) => cue.start)
    .slice(0, 6);

  const anchors: number[] = [];
  const anchorCount = Math.min(4, Math.max(1, Math.floor(duration / 600)));
  for (let index = 1; index <= anchorCount; index += 1) {
    anchors.push((duration * index) / (anchorCount + 1));
  }

  const merged = [...semantic, ...anchors]
    .filter((time) => Number.isFinite(time) && time >= 0 && time <= duration)
    .map((time) => Math.max(0, Math.min(duration - 0.5, time)));

  return Array.from(new Set(merged.map((time) => Math.round(time)))).slice(
    0,
    MAX_VISUAL_CANDIDATES
  );
}

async function extractCurrentVideo(): Promise<ExtractResult> {
  const videoElement = getVideoElement();
  const playerResponse = getPlayerResponse();
  const videoDetails = playerResponse?.videoDetails;
  const videoId = videoDetails?.videoId ?? getVideoIdFromUrl();

  if (!videoElement || !videoId) {
    return {
      ok: false,
      reason: "NO_VIDEO",
      message: "Open a YouTube video to get started."
    };
  }

  const tracks = getCaptionTracks(playerResponse);
  const selectedTrack = chooseCaptionTrack(tracks);

  if (!selectedTrack) {
    return {
      ok: false,
      reason: "NO_CAPTIONS",
      message: "This video has no captions. Audio transcription is not part of the MVP yet."
    };
  }

  try {
    const captions = await fetchCaptions(selectedTrack);

    if (captions.length === 0) {
      return {
        ok: false,
        reason: "NO_CAPTIONS",
        message: "This video did not return usable caption text."
      };
    }

    const duration =
      Number(videoDetails?.lengthSeconds) ||
      Number(videoElement.duration) ||
      captions.at(-1)?.end ||
      0;

    return {
      ok: true,
      video: {
        id: videoId,
        title: videoDetails?.title ?? document.title.replace(" - YouTube", ""),
        duration,
        url: window.location.href,
        channelName: videoDetails?.author
      },
      captions,
      captionTrack: normalizeTrack(selectedTrack),
      visualCandidateTimestamps: chooseVisualCandidates(captions, duration)
    };
  } catch {
    return {
      ok: false,
      reason: "CAPTION_FETCH_FAILED",
      message: "Could not fetch captions for this video."
    };
  }
}

function wait(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function seekVideo(video: HTMLVideoElement, timestamp: number): Promise<void> {
  return new Promise((resolve) => {
    let settled = false;
    const finish = () => {
      if (settled) return;
      settled = true;
      video.removeEventListener("seeked", finish);
      resolve();
    };

    video.addEventListener("seeked", finish, { once: true });
    video.currentTime = timestamp;
    window.setTimeout(finish, 1500);
  });
}

async function captureVisibleTab(): Promise<string> {
  const response = await chrome.runtime.sendMessage({
    type: "VIDSCRIBE_CAPTURE_VISIBLE_TAB"
  });

  if (!response?.ok || !response.dataUrl) {
    throw new Error(response?.error ?? "Visible tab capture failed");
  }

  return response.dataUrl;
}

async function captureFrames(timestamps: number[]): Promise<CaptureFramesResult> {
  const video = getVideoElement();
  if (!video) {
    return { ok: false, message: "No video element found." };
  }

  const uniqueTimestamps = Array.from(
    new Set(
      timestamps
        .map((timestamp) => Number(timestamp))
        .filter((timestamp) => Number.isFinite(timestamp) && timestamp >= 0)
        .map((timestamp) =>
          Math.min(Math.max(0, timestamp), Math.max(0, video.duration - 0.5))
        )
    )
  ).slice(0, MAX_VISUAL_CANDIDATES);

  const originalTime = video.currentTime;
  const wasPaused = video.paused;
  const frames: Array<{
    timestamp: number;
    dataUrl: string;
    source: "tab-screenshot";
  }> = [];

  try {
    video.pause();

    for (const timestamp of uniqueTimestamps) {
      await seekVideo(video, timestamp);
      await wait(350);
      const dataUrl = await captureVisibleTab();
      frames.push({
        timestamp: video.currentTime,
        dataUrl,
        source: "tab-screenshot"
      });
    }

    return { ok: true, frames };
  } catch (error) {
    return {
      ok: false,
      message: error instanceof Error ? error.message : "Frame capture failed"
    };
  } finally {
    await seekVideo(video, originalTime);
    if (!wasPaused) {
      void video.play();
    }
  }
}

function seekTo(timestamp: number) {
  const video = getVideoElement();
  if (!video) return;
  video.currentTime = Math.max(0, Math.min(timestamp, video.duration || timestamp));
  void video.play();
}
