import { z } from "zod";

export const captionCueSchema = z.object({
  start: z.number().nonnegative(),
  end: z.number().nonnegative(),
  text: z.string().min(1)
});

export const captionTrackSchema = z.object({
  languageCode: z.string().optional(),
  name: z.string().optional(),
  kind: z.string().optional(),
  isAutoGenerated: z.boolean(),
  url: z.string().url().optional()
});

export const videoContextSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  duration: z.number().nonnegative(),
  url: z.string().url(),
  channelName: z.string().optional()
});

export const visualFrameSchema = z.object({
  timestamp: z.number().nonnegative(),
  dataUrl: z.string().startsWith("data:image/"),
  source: z.enum(["tab-screenshot", "canvas"]).default("tab-screenshot")
});

export const definitionSchema = z.object({
  term: z.string(),
  explanation: z.string()
});

export const noteSectionSchema = z.object({
  id: z.string(),
  title: z.string(),
  startSeconds: z.number().nonnegative(),
  endSeconds: z.number().nonnegative().optional(),
  bullets: z.array(z.string()),
  definitions: z.array(definitionSchema).default([]),
  examples: z.array(z.string()).default([]),
  visual: z.string().optional(),
  sourceChunk: z.number().int().nonnegative().optional()
});

export const noteDocumentSchema = z.object({
  video: videoContextSchema,
  generatedAt: z.string(),
  sections: z.array(noteSectionSchema),
  failedChunkCount: z.number().int().nonnegative().default(0),
  warnings: z.array(z.string()).default([])
});

export const generateNotesRequestSchema = z.object({
  video: videoContextSchema,
  captions: z.array(captionCueSchema).min(1),
  captionTrack: captionTrackSchema.optional(),
  frames: z.array(visualFrameSchema).default([])
});

export const jobStatusSchema = z.enum([
  "queued",
  "running",
  "completed",
  "partial",
  "failed"
]);

export const jobProgressSchema = z.object({
  completedChunks: z.number().int().nonnegative(),
  totalChunks: z.number().int().nonnegative(),
  currentMessage: z.string()
});

export const noteJobSchema = z.object({
  jobId: z.string(),
  status: jobStatusSchema,
  progress: jobProgressSchema,
  document: noteDocumentSchema.optional(),
  errors: z.array(z.string()).default([]),
  usage: z
    .object({
      inputTokens: z.number().int().nonnegative(),
      outputTokens: z.number().int().nonnegative()
    })
    .optional()
});

export type CaptionCue = z.infer<typeof captionCueSchema>;
export type CaptionTrack = z.infer<typeof captionTrackSchema>;
export type VideoContext = z.infer<typeof videoContextSchema>;
export type VisualFrame = z.infer<typeof visualFrameSchema>;
export type NoteSection = z.infer<typeof noteSectionSchema>;
export type NoteDocument = z.infer<typeof noteDocumentSchema>;
export type GenerateNotesRequest = z.infer<typeof generateNotesRequestSchema>;
export type JobStatus = z.infer<typeof jobStatusSchema>;
export type JobProgress = z.infer<typeof jobProgressSchema>;
export type NoteJob = z.infer<typeof noteJobSchema>;
